
import static java.lang.Double.NaN;
import java.util.ArrayList;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author eduar
 */
public class Calculadora extends javax.swing.JFrame {
    private String cadena="";
    private String cadenaMetodos="";
    
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resultadosTF = new javax.swing.JTextField();
        n7BT = new javax.swing.JButton();
        n0BT = new javax.swing.JButton();
        n5BT = new javax.swing.JButton();
        n8BT = new javax.swing.JButton();
        n9BT = new javax.swing.JButton();
        n3BT = new javax.swing.JButton();
        n2BT = new javax.swing.JButton();
        puntoBT = new javax.swing.JButton();
        n4BT = new javax.swing.JButton();
        n1BT = new javax.swing.JButton();
        potenciaBT = new javax.swing.JButton();
        parentesisDerBT = new javax.swing.JButton();
        multBT = new javax.swing.JButton();
        divBT = new javax.swing.JButton();
        parentesisIzqBT = new javax.swing.JButton();
        n6BT = new javax.swing.JButton();
        delBT = new javax.swing.JButton();
        sumaBT = new javax.swing.JButton();
        restaBT = new javax.swing.JButton();
        igualBT = new javax.swing.JButton();
        negativoBT = new javax.swing.JButton();
        clearBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        n7BT.setText("7");
        n7BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n7BTActionPerformed(evt);
            }
        });

        n0BT.setText("0");
        n0BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n0BTActionPerformed(evt);
            }
        });

        n5BT.setText("5");
        n5BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n5BTActionPerformed(evt);
            }
        });

        n8BT.setText("8");
        n8BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n8BTActionPerformed(evt);
            }
        });

        n9BT.setText("9");
        n9BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n9BTActionPerformed(evt);
            }
        });

        n3BT.setText("3");
        n3BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n3BTActionPerformed(evt);
            }
        });

        n2BT.setText("2");
        n2BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n2BTActionPerformed(evt);
            }
        });

        puntoBT.setText(".");
        puntoBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntoBTActionPerformed(evt);
            }
        });

        n4BT.setText("4");
        n4BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n4BTActionPerformed(evt);
            }
        });

        n1BT.setText("1");
        n1BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n1BTActionPerformed(evt);
            }
        });

        potenciaBT.setText("^");
        potenciaBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potenciaBTActionPerformed(evt);
            }
        });

        parentesisDerBT.setText("(");
        parentesisDerBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parentesisDerBTActionPerformed(evt);
            }
        });

        multBT.setText("*");
        multBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multBTActionPerformed(evt);
            }
        });

        divBT.setText("/");
        divBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divBTActionPerformed(evt);
            }
        });

        parentesisIzqBT.setText(")");
        parentesisIzqBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parentesisIzqBTActionPerformed(evt);
            }
        });

        n6BT.setText("6");
        n6BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n6BTActionPerformed(evt);
            }
        });

        delBT.setText("delete");
        delBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBTActionPerformed(evt);
            }
        });

        sumaBT.setText("+");
        sumaBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumaBTActionPerformed(evt);
            }
        });

        restaBT.setText("-");
        restaBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaBTActionPerformed(evt);
            }
        });

        igualBT.setText("=");
        igualBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igualBTActionPerformed(evt);
            }
        });

        negativoBT.setText("(-)");
        negativoBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negativoBTActionPerformed(evt);
            }
        });

        clearBT.setText("clear");
        clearBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resultadosTF)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(n7BT, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n8BT, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n9BT, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(potenciaBT, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(n0BT, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(puntoBT, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(parentesisDerBT, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(parentesisIzqBT, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(n4BT, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(n5BT, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(n3BT, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(n2BT, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(n1BT, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n6BT, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(multBT, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(divBT, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(delBT, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(restaBT, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(negativoBT, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sumaBT, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(clearBT, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(igualBT, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(resultadosTF, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(n7BT, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n8BT, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n9BT, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(potenciaBT, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(n4BT, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(n5BT, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(n6BT, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(multBT, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sumaBT, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(n3BT, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n2BT, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n1BT, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(divBT, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(restaBT, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(n0BT, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(puntoBT, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(parentesisDerBT, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(parentesisIzqBT, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(negativoBT, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(delBT, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(igualBT, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearBT, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void n7BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n7BTActionPerformed
        cadena+="7";
        cadenaMetodos+="7";
        resultadosTF.setText(cadena);
    }//GEN-LAST:event_n7BTActionPerformed

    private void n8BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n8BTActionPerformed
        cadena+="8";
        cadenaMetodos+="8";
        resultadosTF.setText(cadena);
    }//GEN-LAST:event_n8BTActionPerformed

    private void n9BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n9BTActionPerformed
        cadena+="9";
        cadenaMetodos+="9";
        resultadosTF.setText(cadena);
    }//GEN-LAST:event_n9BTActionPerformed

    private void potenciaBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potenciaBTActionPerformed
        cadena+="^";
        cadenaMetodos+="^";
        resultadosTF.setText(cadena);
    }//GEN-LAST:event_potenciaBTActionPerformed

    private void delBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBTActionPerformed
        if(cadena.length()>0){
            cadena=cadena.substring(0, cadena.length()-1);
            cadenaMetodos=cadenaMetodos.substring(0, cadenaMetodos.length()-1);
            resultadosTF.setText(cadena);
        }
    }//GEN-LAST:event_delBTActionPerformed

    private void n4BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n4BTActionPerformed
        cadena+="4";
        cadenaMetodos+="4";
        resultadosTF.setText(cadena);
    }//GEN-LAST:event_n4BTActionPerformed

    private void n5BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n5BTActionPerformed
        cadena+="5";
        cadenaMetodos+="5";
        resultadosTF.setText(cadena);
    }//GEN-LAST:event_n5BTActionPerformed

    private void n6BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n6BTActionPerformed
        cadena+="6";
        cadenaMetodos+="6";
        resultadosTF.setText(cadena);
    }//GEN-LAST:event_n6BTActionPerformed

    private void multBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multBTActionPerformed
        cadena+="*";
        cadenaMetodos+="*";
        resultadosTF.setText(cadena);
    }//GEN-LAST:event_multBTActionPerformed

    private void sumaBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumaBTActionPerformed
        cadena+="+";
        cadenaMetodos+="+";
        resultadosTF.setText(cadena);
    }//GEN-LAST:event_sumaBTActionPerformed

    private void n3BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n3BTActionPerformed
        cadena+="3";
        cadenaMetodos+="3";
        resultadosTF.setText(cadena);
    }//GEN-LAST:event_n3BTActionPerformed

    private void n2BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n2BTActionPerformed
        cadena+="2";
        cadenaMetodos+="2";
        resultadosTF.setText(cadena);
    }//GEN-LAST:event_n2BTActionPerformed

    private void n1BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n1BTActionPerformed
        cadena+="1";
        cadenaMetodos+="1";
        resultadosTF.setText(cadena);
    }//GEN-LAST:event_n1BTActionPerformed

    private void divBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divBTActionPerformed
        cadena+="/";
        cadenaMetodos+="/";
        resultadosTF.setText(cadena);
    }//GEN-LAST:event_divBTActionPerformed

    private void restaBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaBTActionPerformed
        cadena+="-";
        cadenaMetodos+="-";
        resultadosTF.setText(cadena);
    }//GEN-LAST:event_restaBTActionPerformed

    private void n0BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n0BTActionPerformed
        cadena+="0";
        cadenaMetodos+="0";
        resultadosTF.setText(cadena);
    }//GEN-LAST:event_n0BTActionPerformed

    private void puntoBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntoBTActionPerformed
        cadena+=".";
        cadenaMetodos+=".";
        resultadosTF.setText(cadena);
    }//GEN-LAST:event_puntoBTActionPerformed

    private void parentesisDerBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parentesisDerBTActionPerformed
        cadena+="(";
        cadenaMetodos+="(";
        resultadosTF.setText(cadena);
    }//GEN-LAST:event_parentesisDerBTActionPerformed

    private void parentesisIzqBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parentesisIzqBTActionPerformed
        cadena+=")";
        cadenaMetodos+=")";
        resultadosTF.setText(cadena);
    }//GEN-LAST:event_parentesisIzqBTActionPerformed

    private void negativoBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negativoBTActionPerformed
        cadena+="-";
        cadenaMetodos+="$";
        resultadosTF.setText(cadena);
    }//GEN-LAST:event_negativoBTActionPerformed

    private void clearBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBTActionPerformed
        cadena="";
        cadenaMetodos="";
        resultadosTF.setText(cadena);
    }//GEN-LAST:event_clearBTActionPerformed

    private void igualBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igualBTActionPerformed
        boolean valido;
        ArrayList<String> postfija= new ArrayList();
        double res=0;
             
        valido=metodosCalculadora.estaBalanceado(cadenaMetodos);
        if(valido){
            //System.out.println("1");
            valido=metodosCalculadora.cadenaCorrecta(cadenaMetodos);
            if(valido){
                //System.out.println("2");
                postfija=metodosCalculadora.convertirPostfija(cadenaMetodos);
                try{
                    res=metodosCalculadora.evalua(postfija);
                }
                catch(Exception e){
                    //System.out.println("3");
                    valido=false;
                }   
            }
        }
        if(!valido||res==NaN){
            cadena="";
            cadenaMetodos="";
            resultadosTF.setText("No podemos resolver el problema planteado.");
        }
        else{
            cadena=""+res;
            cadenaMetodos=""+res;
            resultadosTF.setText(cadena);
        }
    }//GEN-LAST:event_igualBTActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearBT;
    private javax.swing.JButton delBT;
    private javax.swing.JButton divBT;
    private javax.swing.JButton igualBT;
    private javax.swing.JButton multBT;
    private javax.swing.JButton n0BT;
    private javax.swing.JButton n1BT;
    private javax.swing.JButton n2BT;
    private javax.swing.JButton n3BT;
    private javax.swing.JButton n4BT;
    private javax.swing.JButton n5BT;
    private javax.swing.JButton n6BT;
    private javax.swing.JButton n7BT;
    private javax.swing.JButton n8BT;
    private javax.swing.JButton n9BT;
    private javax.swing.JButton negativoBT;
    private javax.swing.JButton parentesisDerBT;
    private javax.swing.JButton parentesisIzqBT;
    private javax.swing.JButton potenciaBT;
    private javax.swing.JButton puntoBT;
    private javax.swing.JButton restaBT;
    private javax.swing.JTextField resultadosTF;
    private javax.swing.JButton sumaBT;
    // End of variables declaration//GEN-END:variables
}
